[build]
  # Command to start the custom dev server
  command = "node start-dev-server.js"
  # Publish directory (use the one your dev server serves from)
  publish = "public"

[functions]
  # Use Node.js runtime for serverless functions
  node_bundler = "esbuild"

[[plugins]]
  # Optional: Include the Next.js plugin if applicable
  package = "@netlify/plugin-nextjs"