[build]
  command = "CI='' npm run build"
  publish = "dist"  # or "build" depending on your build output directory

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18"  # or whatever Node version you're using 